import Head from "next/head";
// import { Camera, CameraResultType } from "@capacitor/camera";
import Link from "next/link";
// import { Camera, CameraResultType } from "@capacitor/camera";

import styles from "../styles/Home.module.css";

export default function Home() {
  // const takePhoto = async () => {
  //   const result = await CameraPreview.capture(cameraPreviewPictureOptions);
  //   console.log({ result });

  //   // setImage([...images, `data:image/jpeg;base64,${result.value}`]);

  //   // image.setAttribute("alt", "script div");
  //   // image.setAttribute("src", `data:image/jpeg;base64,${result.value}`);
  //   // let c = document.createElement("canvas");
  //   // let ctx = c.getContext("2d");
  //   // if (ctx) {
  //   //   ctx.canvas.width = 500;
  //   //   ctx.canvas.height = 500;
  //   //   ctx.drawImage(image, 0, 0);
  //   //   var imgInfo = c.toDataURL("image/png");
  //   //   console.log({ imgInfo });
  //   // }
  // };
  // React.useEffect(() => {
  //   CameraPreview.start({
  //     parent: "content",
  //     toBack: true,
  //     position: "front",
  //   });
  // }, []);
  // const takePicture = async () => {
  //   const image = await Camera.getPhoto({
  //     quality: 90,
  //     allowEditing: true,
  //     resultType: CameraResultType.Uri,
  //   });

  //   // image.webPath will contain a path that can be set as an image src.
  //   // You can access the original file using image.path, which can be
  //   // passed to the Filesystem API to read the raw data of the image,
  //   // if desired (or pass resultType: CameraResultType.Base64 to getPhoto)
  //   var imageUrl = image.webPath;
  //   console.log({ image });
  //   // Can be set to the src of an image now
  //   // imageElement.src = imageUrl;
  // };
  return (
    <div className={styles.container}>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Link href="/">Home</Link>
        </h1>
      </main>

      <footer className={styles.footer}>
        {/* <button onClick={takePicture}>Take Photo</button> */}
      </footer>
    </div>
  );
}
